In [1]:
import numpy as np


In [2]:
#To create arrays

a = np.array([1, 2, 3])

print (a)
b = np.array([[1, 4, 5.0], [3.9, 4, 2.9]])
print(b)

[1 2 3]
[[1.  4.  5. ]
 [3.9 4.  2.9]]


In [3]:
#To get the dimension of an array

a.ndim
# b.ndim

1

In [4]:
# To get the shape of an array

# a.shape
b.shape

(2, 3)

In [5]:
# To get the tpye

a.dtype

dtype('int32')

In [6]:
#To get the size of an array
a.itemsize
#To get the total number of elements
a.size

3

In [7]:
#There for the total number of szie taken by the "a" array is:
a.size * a.itemsize 
# or
a.nbytes

12

In [8]:
#To create an all zeros matrix
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# For all 1s
np.ones((2,3,4), dtype = "int16")

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [10]:
# for other numbers
np.full((2,4), 9, dtype = 'int8')


array([[9, 9, 9, 9],
       [9, 9, 9, 9]], dtype=int8)

In [11]:
# for random decimals
np.random.rand(4,2, 3)

array([[[0.70299065, 0.64616608, 0.08982535],
        [0.80909777, 0.54021427, 0.63617489]],

       [[0.51186217, 0.42389133, 0.42032463],
        [0.25436939, 0.78140525, 0.12053399]],

       [[0.16269373, 0.72013401, 0.63043999],
        [0.67070827, 0.47144548, 0.62407762]],

       [[0.77582031, 0.2178579 , 0.96148121],
        [0.28537579, 0.67260398, 0.16098432]]])

In [12]:
# for random interger values
np.random.randint(-2, 7, size = (3,3,2))

array([[[ 4,  1],
        [ 1,  4],
        [ 2,  5]],

       [[ 1,  0],
        [-1, -2],
        [ 6,  4]],

       [[ 5,  0],
        [ 6,  0],
        [-1,  4]]])

In [13]:
# for identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
# to repeat an array
array = np.array([[1,2,3]])
re = np.repeat(array, 4, axis = 0)
print(re)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [21]:
output = np.ones((5,5))
# print(output)

middle = np.zeros((3,3))
# print(middle)

middle[1,1] = 9
# print(middle)

output[1:-1, 1:-1] = middle
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
########MATHEMATICS IN NUMPY#########
a = np.array([2, 2, 6, 5])
# a + 2
# a - 2
# a **2
# np.sin(a)
# np.cos(a)
np.tan(a)

In [ ]:
##Linear Algebra
a = np.random.randint(2,8,size =  (3, 3))
# print(a)
b = np.random.rand(3,3)
# print(b)
np.matmul(a,b)

#finding determinant
np.linalg.det(a)

In [ ]:
###STATISTICS
a = np.random.randint(100, 322, size = (2,3))
np.min(a)
np.max(a, axis = 0)
np.mean(a)

In [ ]:
##rearranging arrays

a = np.random.randint(-2,4, size = (4,3))
print(a)
b= a.reshape((6,2))
print(b)

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
arr2 = arr.copy()
arr2[1::2] = -1
print(arr)
print(arr2)

In [ ]:
a = np.array([1,2,3])
b = np.repeat(a, 3, axis = 0)
c = np.hstack([ b, a, a, a])
c

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a < b)

In [ ]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
# c = np.hstack([a,b])
np.max([a,b])

In [ ]:
np.set_printoptions(threshold=6)
a = np.arange(20)
a

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
iris[:6]

In [27]:
an_array = np.array([[0, 1, 3, 4],
                                    [6, 5, 2, 7],
                                    [3, 9, 8, 3]])
row = np.array([0, 2, 2, 1])
col = np.arange(4)
print(an_array)
print(row)
print(col)

[[0 1 3 4]
 [6 5 2 7]
 [3 9 8 3]]
[0 2 2 1]
[0 1 2 3]


In [30]:
for r, c in zip(row, col):
    print(an_array[r, c])

0
9
8
7


In [31]:
print(an_array[row, col])

[0 9 8 7]


In [39]:
filter = an_array >= 4
filter
print(an_array[filter])

[4 6 5 7 9 8]


In [40]:
# or
print(an_array[an_array>= 4])

[4 6 5 7 9 8]
